### ISSUE TITLE
[data loss] Pin repo root directory on push

### ISSUE THREAD

**Issue by da2x** [dhappy/git-remote-ipfs#5]
`git push` needs to pin the new IPFS repo address it returns. Otherwise it will be eaten by IPFS’ repository garbage collection.

Expected behaviour: `ipfs pin list | grep Qrepohash` should return the hash, and `ipfs repo gc | grep Qrepohash` *must not*.

Actual behaviour: The opposite.

**Comment by Luflosi** [comment]
I'm thinking about what might happen when the gc runs while `git push` is also running. If `git push` just pins the hash after doing what it currently does, then I think the gc would remove the newly added but not yet pinned stuff. Unfortunately I don't think there is a good way to avoid that but I could be wrong.

**Comment by da2x** [comment]
> Unfortunately I don't think there is a good way to avoid that but I could be wrong.

`ipfs add --pin=true` avoids the timing issue, but not sure if there’s something like that when working with dag.

**Comment by dysbulic** [comment]
I rewrote the remote in javascript and it now pins all data as it is added to IPFS.

It now maintains the commit tree structure rather than flattening everything into a table.

It makes pushing successive commits orders of magnitude faster.

If I decide to port this back to the original go, I'll add pinning there as well. I agree that should be the default behavior.
